epochs: 100
grad_bound: 5.0
log_frequency: 100

dataset:
  name: DatasetGenerator
  asym: False
  train_batch_size: 128
  eval_batch_size: 512
  data_path: ../datasets
  dataset_type: 'FMNIST'
  num_of_workers: 8

model:
  name: ResNet34
  num_classes : 10
  in_channel : 1

optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 1.e-2
  momentum: 0.9
  nesterov: True

scheduler:
  name: CosineAnnealingLR
  T_max: $epochs
  eta_min: 0.001

criterion:
  name: NCEandRCE
  num_classes: 10
  alpha: 10.0
  beta: 0.1
