epochs: 200
grad_bound: 5.0
log_frequency: 100

dataset:
  name: DatasetGenerator
  asym: False
  train_batch_size: 128
  eval_batch_size: 128
  data_path: ../datasets/
  dataset_type: 'CIFAR10'
  num_of_workers: 8

model:
  name: ResNet34
  num_classes : 10
  in_channel : 3

optimizer:
  name: SGD
  lr: 0.02
  weight_decay: 1.e-3
  momentum: 0.9

scheduler:
  name: MultiStepLR
  milestones: [80]
  gamma: 0.01

criterion:
  name: NCEandRCE
  num_classes: 10
  alpha: 5.0
  beta: 0.1
